-- mysqlimport --ignore-lines=1 --fields-terminated-by=, --columns='USER_NM,USER_AGE,PASSWORD,FAMILY_SIZE,NUM_ADULTS,NUM_KIDS,ANNUAL_HOUSEHOLD_INCOME,SHOP_TRIP_FREQ' --host 0.0.0.0 --port 3306 FOOD_WASTE_CONSUMER_DB ./USER_PROFILE.csv
DROP DATABASE IF EXISTS FOOD_WASTE_CONSUMER_DB;

CREATE DATABASE FOOD_WASTE_CONSUMER_DB;

USE FOOD_WASTE_CONSUMER_DB;

DROP TABLE IF EXISTS USER_PROFILE;

CREATE TABLE IF NOT EXISTS USER_PROFILE
(USER_ID bigint primary key,
 USERNAME varchar(128) ,
 EMAIL varchar(128) ,
 PASSWORD varchar(128) ,
 USER_NM varchar(128) ,
 USER_AGE integer,
 FAMILY_MBR_ID bigint,
 FAMILY_SIZE integer,
 NUM_ADULTS integer,
 NUM_KIDS integer,
 ANNUAL_HOUSEHOLD_INCOME DECIMAL UNSIGNED,
 SHOP_TRIP_FREQ INTEGER
);

INSERT INTO USER_PROFILE (USER_ID,
  USERNAME, EMAIL, PASSWORD,
  USER_NM, USER_AGE, FAMILY_MBR_ID,
  FAMILY_SIZE, NUM_ADULTS, NUM_KIDS,
  ANNUAL_HOUSEHOLD_INCOME, SHOP_TRIP_FREQ
)
VALUES (1, "bob", "bob@bob.com", "bob", "Bob McBob", 30, null, 3, 2, 1, 1000000, 5);

INSERT INTO USER_PROFILE (USER_ID,
  USERNAME, EMAIL, PASSWORD,
  USER_NM, USER_AGE, FAMILY_MBR_ID,
  FAMILY_SIZE, NUM_ADULTS, NUM_KIDS,
  ANNUAL_HOUSEHOLD_INCOME, SHOP_TRIP_FREQ
)
VALUES (2, "jane", "jane@jane.com", "jane", "Jane Jane", 25, null, 3, 2, 1, 1000000, 3);

DROP TABLE IF EXISTS USER_GROCERY_RECEIPT;

CREATE TABLE IF NOT EXISTS USER_GROCERY_RECEIPT
(USER_ID bigint,
 RECEIPT_ID bigint,
 UPLOAD_DT date,
 ITEM_ID bigint,
 ITEM_QTY_PRCH decimal unsigned,
 ITEM_UNITS varchar(20)	,
 ITEM_TOTAL_PRICE decimal unsigned,
 ITEM_CATEGORY varchar(30),
 CONSTRAINT groceries_pk PRIMARY KEY (USER_ID, RECEIPT_ID , UPLOAD_DT)
 );




DROP TABLE IF EXISTS USER_GROCERY_ITEM_LKP;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_LKP
(ITEM_ID bigint primary key,
ITEM_NAME varchar(100) );


DROP TABLE IF EXISTS USER_GROCERY_ITEM_WASTE_ACTUAL;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_WASTE_ACTUAL
(USER_ID bigint,
 RECEIPT_ID bigint,
 DATA_ENTRY_DT date,
 ITEM_ID bigint,
 WASTE_AMT decimal unsigned,
 WASTE_UNIT varchar(30),
 CONSTRAINT grocery_waste_pk PRIMARY KEY (USER_ID, RECEIPT_ID , DATA_ENTRY_DT, ITEM_ID)
 );

DROP TABLE IF EXISTS USER_GROCERY_ITEM_WASTE_PRED;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_WASTE_PRED
(USER_ID bigint,
 RECEIPT_ID bigint,
 DATA_ENTRY_DT date,
 ITEM_ID bigint,
 PRED_ASTE_AMT decimal unsigned,
 PRED_WASTE_UNIT varchar(30),
 MODEL_TYPE varchar(20),
 CONSTRAINT grocery_waste_pred_pk PRIMARY KEY (USER_ID, RECEIPT_ID , DATA_ENTRY_DT, ITEM_ID)
 );


DROP TABLE IF EXISTS USER_GROCERY_ITEM_PRCH_FREQ;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_PRCH_FREQ
(USER_ID bigint,
 ITEM_ID bigint,
 FRQ_PRCH_EVER bigint,
 FRQ_PRCH_LAST3_TRIPS integer,
 CONSTRAINT grocery_prch_freq_pk PRIMARY KEY (USER_ID, ITEM_ID)
 );
