DROP DATABASE IF EXISTS FOOD_WASTE_CONSUMER_DB;

CREATE DATABASE FOOD_WASTE_CONSUMER_DB;

USE FOOD_WASTE_CONSUMER_DB;

DROP TABLE IF EXISTS USER_PROFILE;

CREATE TABLE IF NOT EXISTS USER_PROFILE
(USER_ID VARCHAR(128) primary key, /*Login User Name*/
 USER_NM varchar(128) , /*Name of User*/
 USER_AGE integer,
 PASSWORD VARCHAR(128),
 FAMILY_SIZE integer,
 NUM_ADULTS integer,
 NUM_KIDS integer,
 ANNUAL_HOUSEHOLD_INCOME integer, /* Range */
 SHOP_TRIP_FREQ varchar(30)
);

DROP TABLE IF EXISTS USER_GROCERY_RECEIPT;

CREATE TABLE IF NOT EXISTS USER_GROCERY_RECEIPT
(USER_ID VARCHAR(128), /*Login User Name*/
 RECEIPT_ID VARCHAR(128),   /* System Generated ID - Hash Value from Receipt */
 RECEIPT_UPLOAD_DT varchar(30),
 ITEM_ID varchar(30), /* UPC Code */
 ITEM_NAME VARCHAR(100), /* Name from Receipt */
 ITEM_QTY_PRCH decimal(10, 2),
 ITEM_UNITS varchar(20)	,
 ITEM_TOTAL_PRICE decimal(10, 2), /* Price in Dollars */
 ITEM_CATEGORY varchar(100), /* OCR Closest Category */
 CONSTRAINT groceries_pk PRIMARY KEY (USER_ID, RECEIPT_ID, ITEM_ID)
 );


 DROP TABLE IF EXISTS USER_GROCERY_ITEM_WASTE_ACTUAL;

 CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_WASTE_ACTUAL
 (USER_ID VARCHAR(128),
  RECEIPT_ID bigint,
  WASTE_DATA_ENTRY_DT date,
  ITEM_ID bigint,
  ITEM_NAME varchar(100),
  ITEM_CATEGORY varchar(100),
  ITEM_CLASS varchar(100),
  ITEM_SIZE bigint,
  ITEM_TOTAL_PRICE decimal(10,2) unsigned,
  WASTE_AMT decimal(10,2) unsigned,
  WASTE_UNITS varchar(30),
  CONSTRAINT grocery_waste_pk PRIMARY KEY (USER_ID, RECEIPT_ID , WASTE_DATA_ENTRY_DT, ITEM_ID)
  );

DROP TABLE IF EXISTS USER_GROCERY_ITEM_WASTE_PRED;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_WASTE_PRED
(USER_ID VARCHAR(128), /*Login User Name*/
 RECEIPT_ID VARCHAR(128),   /* System Generated ID - Hash Value from Receipt */
 RECEIPT_UPLOAD_DT bigint,
 ITEM_ID bigint, /* UPC Code */
 ITEM_NAME VARCHAR(100), /* Name from Receipt */
 ITEM_QTY_PRCH decimal(10, 2),
 ITEM_UNITS varchar(20)	,
 ITEM_TOTAL_PRICE decimal(10, 2), /* Price in Dollars */
 ITEM_CATEGORY varchar(100), /* OCR Closest Category */
 ITEM_CLASS VARCHAR(30),
 ITEM_SIZE decimal(10, 2),
 DAY bigint,
 ITEM_TOTAL_SIZE decimal(10, 2),
 FAMILY_SIZE integer,
 PER_CAPITA_SIZE decimal(10, 6),
 PER_CAPITA_SIZE_TRIP decimal(10, 6),
 PREVIOUS_SHOP_DATE bigint,
 PREVIOUS_SHOP_SIZE bigint,
 ITEM_SIZE_AVG decimal(10, 6),
 ITEM_SIZE_STDEV varchar(30),
 ITEM_SIZE_Z decimal(10, 6),
 ITEM_SIZE_ALL_AVG decimal(10, 6),
 ITEM_SIZE_ALL_STDEV varchar(30),
 ITEM_SIZE_ALL_Z decimal(10, 6),
 ITEM_DURATION decimal(10, 6),
 TIME_LOSS_COUNTER decimal(10, 6),
 TIME_LOSS bigint,
 TRIP_SIZE_AVG decimal(10, 6),
 TRIP_SIZE_STDEV decimal(10, 6),
 DAYS_BETWEEN_AVG decimal(10, 6),
 DAYS_BETWEEN_STDEV decimal(10, 6),
 PREV_SIZE_Z decimal(10, 6),
 PREV_DATE_Z decimal(10, 6),
 PREV_Z decimal(10, 6),
 SHOPPING_RANK bigint,
 WASTE_AMT varchar(30),
 CONSTRAINT groceries_pk PRIMARY KEY (USER_ID, RECEIPT_ID, ITEM_ID)
 );



DROP TABLE IF EXISTS USER_RECO_GROCERY_EDITS_STG;

CREATE TABLE IF NOT EXISTS USER_RECO_GROCERY_EDITS_STG
(USER_ID VARCHAR(128),
 SHOPPING_TRIP_ID bigint,
 RECOMMENDATION_CATEGORY varchar(100), /* Values - Recommended or Suggested */
 EDIT_DT date,
 ITEM_ID bigint,
 ITEM_NAME varchar(100),
 ITEM_CATEGORY varchar(30),
 RECOMMENDED_QTY bigint,
 ITEM_UNITS varchar(30),
 EDITED_QTY bigint,
 CONSTRAINT grocery_waste_pred_pk PRIMARY KEY (USER_ID, SHOPPING_TRIP_ID , EDIT_DT, ITEM_ID)
 );


DROP TABLE IF EXISTS USER_RECO_GROCERY_EDITS_HIST;

CREATE TABLE IF NOT EXISTS USER_RECO_GROCERY_EDITS_HIST
(USER_ID VARCHAR(128),
 SHOPPING_TRIP_ID bigint,
 RECOMMENDATION_CATEGORY varchar(100), /* Values - Recommended or Suggested */
 EDIT_DT date,
 ITEM_ID bigint,
 ITEM_NAME varchar(100),
 ITEM_CATEGORY varchar(30),
 RECOMMENDED_QTY bigint,
 ITEM_UNITS varchar(30),
 EDITED_QTY bigint,
 CONSTRAINT grocery_waste_pred_pk PRIMARY KEY (USER_ID, SHOPPING_TRIP_ID , EDIT_DT, ITEM_ID)
 );




DROP TABLE IF EXISTS USER_GROCERY_ITEM_PRCH_FREQ;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_PRCH_FREQ
(USER_ID VARCHAR(128),
 ITEM_ID bigint,
 FRQ_PRCH_EVER bigint,
 FRQ_PRCH_LAST3_TRIPS integer,
 CONSTRAINT grocery_prch_freq_pk PRIMARY KEY (USER_ID, ITEM_ID)
 );



DROP TABLE IF EXISTS USER_GROCERY_ITEM_LOOKUP;

CREATE TABLE IF NOT EXISTS USER_GROCERY_ITEM_LOOKUP
(ITEM_ID bigint primary key,
 ITEM_NAME VARCHAR(100),
 ITEM_CATEGORY VARCHAR(30),
 ITEM_CLASS VARCHAR(30),
 ITEM_SIZE decimal(10, 2),
 ITEM_UNITS varchar(30),
 ITEM_DURATION varchar(30)
 );



DROP TABLE IF EXISTS SAMPLE_RECEIPTS;

CREATE TABLE IF NOT EXISTS SAMPLE_RECEIPTS
(USER_ID VARCHAR(128),
 ITEM_ID bigint,
 ITEM_SIZE decimal(10, 2),
 ITEM_QTY_PRCH bigint,
 SHOPPING_DATE bigint,
 RECEIPT_ID bigint,
 ITEM_TOTAL_PRICE decimal(10, 2),
 CONSTRAINT groceries_PK PRIMARY KEY (USER_ID, RECEIPT_ID, ITEM_ID)
 );


DROP TABLE IF EXISTS MODEL_PARAMETERS;

CREATE TABLE IF NOT EXISTS MODEL_PARAMETERS
(VARIABLE VARCHAR(128) primary key,
 COEFFICIENTS decimal(10, 6)
);



DROP TABLE IF EXISTS MODEL_PARAMETERS;

CREATE TABLE IF NOT EXISTS MODEL_PARAMETERS_STAGING_TABLE
(USER_ID VARCHAR(128), /*Login User Name*/
 ITEM_ID bigint, /* UPC Code */
 ITEM_CLASS VARCHAR(30),
 SHOP_TRIP_COUNT bigint,   /* System Generated ID - Hash Value from Receipt */
 ITEM_CATEGORY varchar(100), /* OCR Closest Category */
 ITEM_SIZE_AVG decimal(10, 2),
 DAY bigint,
 RECEIPT_ID bigint,   /* System Generated ID - Hash Value from Receipt */
 RECEIPT_UPLOAD_DT bigint,
 ITEM_NAME VARCHAR(100), /* Name from Receipt */
 ITEM_QTY_PRCH decimal(10, 2),
 ITEM_UNITS varchar(20)	,
 ITEM_TOTAL_PRICE decimal(10, 2), /* Price in Dollars */
 ITEM_SIZE decimal(10, 2),
 ITEM_TOTAL_SIZE decimal(10, 2),
 FAMILY_SIZE integer,
 PER_CAPITA_SIZE decimal(10, 6),
 PER_CAPITA_SIZE_TRIP decimal(10, 6),
 PREVIOUS_SHOP_DATE bigint,
 PREVIOUS_SHOP_SIZE bigint,
 ITEM_SIZE_STDEV decimal(10, 6),
 ITEM_SIZE_Z decimal(10, 6),
 ITEM_SIZE_ALL_AVG decimal(10, 6),
 ITEM_SIZE_ALL_STDEV decimal(10, 6),
 ITEM_SIZE_ALL_Z decimal(10, 6),
 ITEM_DURATION decimal(10, 6),
 TIME_LOSS_COUNTER decimal(10, 6),
 TIME_LOSS bigint,
 TRIP_SIZE_AVG decimal(10, 6),
 TRIP_SIZE_STDEV decimal(10, 6),
 DAYS_BETWEEN_AVG decimal(10, 6),
 DAYS_BETWEEN_STDEV decimal(10, 6),
 PREV_SIZE_Z decimal(10, 6),
 PREV_DATE_Z decimal(10, 6),
 PREV_Z decimal(10, 6),
 WASTE_AMT decimal(10, 2),
 SHOPPING_DATE date,
 SHOPPING_RANK bigint,
 IN_30 bigint,
 IN_90 bigint,
 YEAR_AGO bigint,
 SHOP_TRIP_COUNT_x integer,
 LAST_PURCH_DAY_ITEM integer,
 ITEM_TRIP_COUNT integer,
 SHOP_TRIP_COUNT_y integer,
 ITEM_QTY_AVG bigint,
 ITEM_PRCH_PERC bigint,
 ITEM_FREQ_RANKED integer,
 ITEM_RECENCY_RANKED integer,
 LAST_PURCH_DAY_CAT integer,
 CAT_TOTAL_COUNT integer,
 CAT_TRIP_COUNT integer,
 CAT_SIZE_AVG bigint,
 CAT_QTY_AVG bigint,
 CAT_PRCH_PERC bigint,
 CAT_FREQ_RANKED integer,
 CAT_RECENCY_RANKED integer,
 LAST_PURCH_DAY_CLASS integer,
 CLASS_TOTAL_COUNT integer,
 CLASS_TRIP_COUNT integer,
 CLASS_PRCH_PERC bigint,
 LAST_TRIP bigint,
 SECOND_LAST_TRIP bigint,
 THIRD_LAST_TRIP bigint,
 FOURTH_LAST_TRIP bigint,
 FIFTH_LAST_TRIP bigint,
 SUM_2 bigint,
 SUM_5 bigint,
 WITHIN_30 bigint,
 WITHIN_90 bigint,
 ONE_YEAR_AGO bigint,
 CONSTRAINT groceries_pk PRIMARY KEY (USER_ID, RECEIPT_ID, ITEM_ID)
 );

DROP TABLE IF EXISTS USER_GROCERY_LIST_PREDICTION;

CREATE TABLE IF NOT EXISTS USER_GROCERY_LIST_PREDICTION
(USER_ID VARCHAR(128), /*Login User Name*/
 ITEM_CATEGORY varchar(100), /* OCR Closest Category */
 FAMILY_SIZE integer,
 ITEM_ID bigint, /* UPC Code */
 ITEM_CLASS varchar(100), /* UPC Code */
 FIRST_SIZE decimal(10, 2),
 ITEM_SIZE decimal(10, 2),
 ITEM_TRUE_SIZE decimal(10, 2),
 ITEM_TOTAL_SIZE decimal(10, 2),
 ITEM_SIZE_AVG decimal(10, 2),
 ITEM_SIZE_STDEV decimal(10, 2),
 ITEM_SIZE_Z decimal(10, 2),
 ITEM_SIZE_ALL_AVG decimal(10, 2),
 ITEM_SIZE_ALL_STDEV decimal(10, 2),
 ITEM_SIZE_ALL_Z decimal(10, 2),
 ITEM_QTY_PRCH decimal(10, 2),
 PREVIOUS_SHOP_DATE integer,
 DAYS_BETWEEN_AVG decimal(10, 2),
 DAYS_BETWEEN_STDEV decimal(10, 2),
 PREV_DATE_Z decimal(10, 2),
 PREVIOUS_SHOP_SIZE decimal(10, 2),
 TRIP_SIZE_AVG decimal(10, 2),
 TRIP_SIZE_STDEV decimal(10, 2),
 PREV_SIZE_Z decimal(10, 2),
 PREV_Z decimal(10, 2),
 TIME_LOSS_COUNTER integer,
 TIME_LOSS integer,
 ITEM_FREQ_RANKED integer,
 CAT_FREQ_RANKED integer,
 MARKER integer,
 SECTION VARCHAR(30),
 prediction VARCHAR(30),
 CONSTRAINT groceries_pk PRIMARY KEY (USER_ID, ITEM_ID)
 );
